#!/bin/sh

EXEC=/home/robot/ev3-server/node_modules/.bin/forever
REPO=/home/robot/ev3-server/.git
GIT=/usr/bin/git
FILE=/home/robot/ev3-server/lib/server.js

case "$1" in
        start)
              $GIT --git-dir=REPO pull
              $EXEC $FILE start
esac
