require('move-steering')
require('color-sensor')
require('ultrasonic-sensor')
require('ir-sensor')
require('ev3-js-motor')
require('ev3-js-wait')
require('touch-sensor')

var fs = require('fs')
process.stdin.setEncoding('utf-8')
process.stdin.on('data', function (filePath) {
	var file = fs.readFileSync(filePath, 'utf-8')
	eval(file)
	process.exit()
})
